<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV0OJAcx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV0OJAcx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV0OJAcx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV0OJAcx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV0OJAcx\App_KernelDevDebugContainer([
    'container.build_hash' => 'V0OJAcx',
    'container.build_id' => '0c1d780c',
    'container.build_time' => 1612784727,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV0OJAcx');
