<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvW6TFS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvW6TFS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXvW6TFS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXvW6TFS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXvW6TFS\App_KernelDevDebugContainer([
    'container.build_hash' => 'XvW6TFS',
    'container.build_id' => 'a83dc507',
    'container.build_time' => 1612777070,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvW6TFS');
