<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKEbAulm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKEbAulm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKEbAulm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKEbAulm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKEbAulm\App_KernelDevDebugContainer([
    'container.build_hash' => 'KEbAulm',
    'container.build_id' => 'a4c2e7b0',
    'container.build_time' => 1612784940,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKEbAulm');
